language: node_js
sudo: false

node_js:
  - '5.6.0'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

branches:
  only:
  - master

env:
  global:
  - LOGS_DIR=/tmp/angular-material2-build/logs
  - SAUCE_USERNAME=tinayuangao
  - SAUCE_ACCESS_KEY=2fe58356-5902-4763-b7f0-2b1cc0657f55
  - ARCH=linux-x64
  - BROWSER_PROVIDER_READY_FILE=/tmp/angular-material2-build/readyfile
  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
    - MODE=e2e

matrix:
  fast_finish: true

install:
  - npm install

before_script:
  - mkdir -p $LOGS_DIR

script:
  - ./scripts/ci/build-and-test.sh

cache:
  directories:
    - node_modules
    - $HOME/.pub-cache
